version: '3'
services:
  zookeeper:
    container_name: zookeeper
    build: zookeeper/.
    ports: 
     - "2181:2181"
    network_mode: host
  kafka:
    container_name: kafka
    build: kafka/.
    ports:
     - "9092:9092"
    network_mode: host
    depends_on:
     - zookeeper
  kafka2:
    container_name: kafka2
    build: kafka2/.
    ports:
     - "9092:9092"
    network_mode: host
    depends_on:
     - kafka


